  ## Numpy

- NumPy is a Python library used for working with arrays.

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.- NumPy was created in 2005 by Travis Oliphant. It is  an open source project and you can use it freely.

- NumPy stands for Numerical Python.

- NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering.

- The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. ython.



## Installation of NumPy

- If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
- Install it using this command:

In [10]:
!pip install numpy

### How to import NumPy

- Once NumPy is installed, import it in your applications by adding the import keyword:

In [15]:
import numpy as np

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Why use NumPy?

- Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

## Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).
- nested array: are arrays that have arrays as their elements.

In [24]:
# Creating numpy in (0D)

import numpy as np

arr = np.array(42)

print(arr)

42


In [17]:
# Creating numpy (1D)
a = np.array([1,2,3,])
print(a)

[1 2 3]


In [108]:
# Creating numpy in (2D)

a = np.array([[1,2,3],[4,5,6]])
            
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# Creating numpy in (3D)

a = np.array([[[1,2,3,],[4,5,6],[7,8,9,]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
# Creating numpy in (4D)

a = np.array([[[[1,2,3],[6,7,8],[23,56,78]]]])
print(a)

[[[[ 1  2  3]
   [ 6  7  8]
   [23 56 78]]]]


In [17]:
# Creating numpy in (5D)

a = np.array([[[[[10,20,30],[40,50,50],[90,79,50]]]]])
print(a)

[[[[[10 20 30]
    [40 50 50]
    [90 79 50]]]]]


### Initial place holders

In [22]:
# Creating intial place holders with Zeros
# (2,3,4) 2 is size,3 is rows,4 is coloums

a = np.zeros([2,3,4])
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [40]:
a = np.zeros([4,3,4])
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [42]:
# Creating intial place holders with ones
# (2,3,4) 2 is size,3 is rows,4 is coloums

a = np.ones([2,3,4])
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [44]:
a = np.ones([3,5,5])
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [48]:
# Creating an array of evenly space value (step value)
# steps = n-1 (n=2)

d = np.arange(1,20,2)
print(d)

[ 1  3  5  7  9 11 13 15 17 19]


In [50]:
# steps = n-1 (n=5)
d = np.arange(1,20,5)
print(d)

[ 1  6 11 16]


In [54]:
# Creating array line space ( num of spaces)
# 5 is no of samples

a = np.linspace(1,20,5)
print(a)

[ 1.    5.75 10.5  15.25 20.  ]


In [56]:
# 10 is no of samples

b = np.linspace(1,50,10)
print(b)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [121]:
# Examples

i = np.array([[[1,2,3],[4,5,6]],
              [[8,6,5],[6,8,9]],
               [[5,7,6],[9,4,5]]])
print(i)

[[[1 2 3]
  [4 5 6]]

 [[8 6 5]
  [6 8 9]]

 [[5 7 6]
  [9 4 5]]]


In [129]:
j= np.array([[2,3,4],[8,9,7],
             [5,6,8],[3,5,4]])
print(j)

[[2 3 4]
 [8 9 7]
 [5 6 8]
 [3 5 4]]


In [7]:
import numpy as np

In [75]:
! pip install numpy

In [13]:
# Creating Constant array
# 1D
a = np.full((5),10) # coloums
print(a)
print(a.ndim)

[10 10 10 10 10]
1


In [35]:
# 2D
a = np.full((4,5),10)
print(a)
print(a.ndim ,"no of dimensions")

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
2 no of dimensions


In [37]:
# 3D
a = np.full((3,4,5),10)
print(a)
print(a.ndim)

[[[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]]
3


### Identity matrix

In [39]:
# Creating Identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# Creating an array with random values
np.random.random((2,5))

array([[0.51385499, 0.94787843, 0.33970443, 0.38274386, 0.69202709],
       [0.22031279, 0.03588144, 0.7164139 , 0.27368883, 0.01024715]])

In [92]:
# Creating an array with random integer values
np.random.randint(1,50)


26

## Array attributes

- This section covers the ndim, shape, size,length (len) and dtype attributes of an array.

In [31]:
# to fiond no of dimensions
a=np.array([[1,3,5],
            [5,6,7],
            [8,9,6]])
print(a.ndim)

2


In [33]:
# To find Size of an array (no of elements in matrix)
a=np.array([[1,3,5],
            [5,6,7],
            [8,9,6]])
print(a.shape)

(3, 3)


In [35]:
# To find shape of array(no of rows and coloums)
a= np.array([[9,0,4],
              [4,6,3],
              [1,2,1]])
print(a.size)

9


In [120]:
# To find length of matrix (no of rows)
a=np.array([[3,5,6],
            [5,9,8],
            [8,9,7]])
print(len(a))

3


In [37]:
# to know to data type
a.dtype

dtype('int32')

## NumPy Array Indexing

- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [122]:
# Access of array elements
# 1D
a = np.array([2,3,4,5,6,7,89])
print(a[4])

6


### Access 2-D Arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [130]:
# 2D
a = np.array([[3,4,5],  #0
              [5,7,8],  #1
              [8,9,3]]) #2
print(a[2,2])
print(a[1,0])

3
5


### Access 3-D Arrays

- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [144]:
# 3D
a = np.array([[[2,4,5],[3,5,6]],
               [[8,9,67],[4,6,8]],
              [[3,2,1],[3,4,6]]])
print(a[2,1,1])
               

4


In [146]:
a = np.array([[[2,4,5],[3,5,6]],
               [[8,9,67],[4,6,8]],
              [[3,2,1],[3,4,6]]])
print(a[2,1,0])
               

3


In [3]:
import numpy as np

In [56]:
a= np.array([[[[1,3,4],[3,7,8]]],
             [[[2,3,4],[3,5,6]]],
             [[[2,3,4],[3,5,6]]]])
print(a[1,0,1])
a.ndim
             

[3 5 6]


4

## Data Types in NumPy

- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer

- b - boolean

- u - unsigned integer

- f - float

- c - complex float

- m - timedelta

- M - datetime

- O - object

- S - string

- U - unicode string

- V - fixed chunk of memory for other type ( void )

In [62]:
# String
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [70]:
# Integer
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Converting Data Type on Existing Arrays

- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [81]:
#Change data type from float to integer by using 'i' as parameter value:
a = np.array([1.1, 2.1, 3.1])

b= a.astype('i')

print(b)
print(b.dtype)

[1 2 3]
int32


In [83]:
#Change data type from integer to boolean:
a= np.array([-1, 0,4,5])

b = a.astype(bool)

print(b)
print(b.dtype)

[ True False  True  True]
bool


In [85]:
#Change data type from integer to float:
a= np.array([-1, 0,4,5])

b = a.astype('f')

print(b)
print(b.dtype)

[-1.  0.  4.  5.]
float32


## NumPy Array Copy vs View

- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

- The copy should not be affected by the changes made to the original array.

In [88]:
import numpy as np
#The copy should not be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 54

print(arr)
print(x)

[54  2  3  4  5]
[1 2 3 4 5]


### View

In [93]:
import numpy as np
##The view should  be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 20

print(arr)
print(x)

[20  2  3  4  5]
[20  2  3  4  5]


In [97]:
# shape
a = np.array([[3,4,5],  
              [5,7,8],  
              [8,9,3]]) 
print(a.shape)


(3, 3)


### Reshaping array

- Using arr.reshape() will give a new shape to an array without changing the data. the reshape method, the array we want to produce needs to have the same number of elements as the original array.

In [119]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [107]:
#Convert the following 1-D array with 12 elements into a 2-D array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 11, 9, 10, 11, 12, 13, 14])

newarr = arr.reshape(7, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 11]
 [ 9 10]
 [11 12]
 [13 14]]


In [111]:
#Convert the following 1-D array with 12 elements into a 3-D arrray

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [123]:
#Convert the following 2-D array with 12 elements into a 1-D arrray

arr = np.array([[1, 2, 3, 4], 
    [5, 6, 7, 8],[ 9, 10, 11, 12]])

newarr = arr.reshape(12)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [125]:
#Convert the following 2-D array with 12 elements into a 3-D arrray

arr = np.array([[1, 2, 3, 4], 
    [5, 6, 7, 8],[ 9, 10, 11, 12]])

newarr = arr.reshape(1,4,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [129]:
#Convert the following 3-D array with 12 elements into a 2-D arrray
arr = np.array([[[1, 2, 3, 4]], 
    [[5, 6, 7, 8]],[[ 9, 10, 11, 12]]])

newarr = arr.reshape(3,4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [133]:
#Convert the following 3-D array with 12 elements into a 1-D arrray
arr = np.array([[[1, 2, 3, 4]], 
    [[5, 6, 7, 8]],[[ 9, 10, 11, 12]]])

newarr = arr.reshape(12)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [141]:
# Python Program to create
# a data type object
x = np.array([[5,2],[3,12]])
y = np.array([[2,9],[4,8]])

In [143]:
# Addition of two Arrays
print(x + y)
print(np.add(x, y))

[[ 7 11]
 [ 7 20]]
[[ 7 11]
 [ 7 20]]


In [147]:
# subtract of the elements
print(x - y)
print(np.subtract(x, y))

[[ 3 -7]
 [-1  4]]
[[ 3 -7]
 [-1  4]]


In [149]:
#multiplication or  product
print(x * y)
print(np.multiply(x, y))



[[10 18]
 [12 96]]
[[10 18]
 [12 96]]


In [151]:
#division
print(x / y)
print(np.divide(x, y))

[[2.5        0.22222222]
 [0.75       1.5       ]]
[[2.5        0.22222222]
 [0.75       1.5       ]]


In [153]:
#square root
print(np.sqrt(x))
print(np.sqrt(y))

[[2.23606798 1.41421356]
 [1.73205081 3.46410162]]
[[1.41421356 3.        ]
 [2.         2.82842712]]


In [155]:
# sort (assending odder)
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


### NumPy Array Slicing

- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [160]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:4])

[1 2 3 4]


In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-3])

[1 2 3 4]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-3])

[4]


In [43]:
# Slicing 2-D Arrays 

import numpy as np

arr = np.array([[1, 2, 3, 4, 5],   #0
                [6, 7, 8, 9, 10]])  #1

print(arr[1, 1:4])

[7 8 9]


In [45]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],   #0
                
                [6, 7, 8, 9, 10]])  #1

print(arr[1:2, 1])

[7]


In [121]:

             #0  #1 #2
a = np.array([[3, 4, 5],  #0
              [5, 7, 8],  #1
              [8, 9, 3],
              [4,7,8]]) 
print(a[2:3,1:3])

[[9 3]]


In [119]:
a = np.array([[13, 9, 35],  #0
              [58, 74, 88],  #1
              [88, 98, 3]]) #2 
print(a[1:3,1:2])

[[74]
 [98]]


In [215]:
a = np.array([[[[13, 9, 35]]],  #0
              [[[58, 74, 88]]],  #1
              [[[88, 98, 3]]]]) #2 
print(a[0:1])


[[[[13  9 35]]]]
